--Revenue Analysis
-- 1. Total revenue generated by the Ecommerce platfor.
SELECT sum(total_amount) as Total_Revenue
FROM orders;

-- 2. Total revenue genetated per product
SELECT a.product_id,
	   b.product_name,
	   sum(c.total_amount) as Revenue
FROM order_items a left Join products b ON a.product_id = b.product_id
LEFT JOIN orders c on a.order_id = c.order_id
GROUP BY a.product_id,b.product_name
ORDER BY 3 DESC;


--Customer Insights
-- 1. Top 5 customers by spending
SELECT a.customer_id,
	   b.customer_name,
	   sum(a.total_amount)
FROM orders a LEFT JOIN customers b on a.customer_id = b.customer_id
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 5;

-- 2. CUstomers that have not made any purchase
SELECT customer_id
FROM customers
WHERE customer_id NOT IN (SELECT customer_id from orders);

-- Product Trend
-- 1. Top 3 best-selling products
SELECT a.product_id,
	   b.product_name,
	   sum(a.quantity) as Quantity_sold
FROM order_items a LEFT JOIN products b on a.product_id = b.product_id
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 3;

-- 2. products that are out of stock
SELECT product_name
FROM products
WHERE product_stock_quantity < 0;

select * from order_items;
select * from orders;
select * from products;
select * from customers;